name: Build CSS

on:
  push:
    branches: [ testing, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Create ephemeral Tailwind input
        run: echo '@tailwind base;@tailwind components;@tailwind utilities;' > .tmp-in.css

      - name: Build CSS with Tailwind (no repo deps)
        run: npx tailwindcss@3.4.18 -c tailwind.config.js -i ./.tmp-in.css -o ./assets/site.css --minify

      - name: Remove temp file
        run: rm .tmp-in.css

      - name: Commit the built CSS
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Build CSS"
          file_pattern: assets/site.css
